language: generic

env:
  global:
    - CIBW_BEFORE_BUILD="{pip} install numpy" CIBW_SKIP="cp33-*”
    - CIBW_TEST_COMMAND="obspy-runtests -r --node=travis-wheel-builder --no-flake8"

#services: [docker]
os: osx

script:
    - wget https://files.pythonhosted.org/packages/c5/f5/9a6150bc707bfb82e1d0533f83d3a7ef00ae3bdb2b8c8f85f5ac2d3b2bd9/obspy-1.1.0.zip
    - unzip -e obspy-1.1.0.zip
    - sudo pip install cibuildwheel numpy
    # First build for OSX.
    - cibuildwheel --platform macos --output-dir wheelhouse obspy-1.1.0
    # Then for Linux and Python 3.x. Only works for platforms that have matplotlib wheels (no 32bit).
    #- CIBW_BEFORE_BUILD="{pip} install numpy" CIBW_SKIP="cp27-* cp33-* *i686*" CIBW_TEST_COMMAND="obspy-runtests -r --node=travis-wheel-builder --no-flake8" cibuildwheel --platform linux --output-dir wheelhouse obspy-1.1.0
    # And finally for Linux and Python 2.7. Only works for platforms that have matplotlib wheels (no 32bit).
    #- CIBW_BEFORE_BUILD="{pip} install numpy mock subprocess32==3.5.0rc1" CIBW_SKIP="cp3*i686*" CIBW_TEST_COMMAND="obspy-runtests -r --node=travis-wheel-builder --no-flake8" cibuildwheel --platform linux --output-dir wheelhouse obspy-1.1.0
