language: generic

env:
  global:
    - CIBW_BEFORE_BUILD="{pip} install numpy matplotlib==1.5.3"
    # ObsPy does not work on Python 3.3.
    - CIBW_SKIP="cp33-*"

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: linux

script:
    - wget https://files.pythonhosted.org/packages/c5/f5/9a6150bc707bfb82e1d0533f83d3a7ef00ae3bdb2b8c8f85f5ac2d3b2bd9/obspy-1.1.0.zip
    - unzip -e obspy-1.1.0.zip
    - sudo pip install cibuildwheel numpy
    - cibuildwheel --output-dir wheelhouse obspy-1.1.0
